# Staging Certificate Workflow

# steven soundship ðŸš€ ~/.files/homelab                                                                                                                                                                              main 4 U / 10 M -- 01:37:44 UTC
#  >  cat ~/.step/ca_password.txt

# mkdir -p ~/.nginx/certs/live/symbology.lofi
# step ca certificate symboloy.lofi ~/.nginx/certs/live/symbology.lofi/fullchain.pem ~/.nginx/certs/live/symbology.lofi/privkey.pem --san "symbology.lofi" --not-after 24h
# mkdir -p ~/.nginx/certs/live/api.symbology.lofi
# step ca certificate api.symboloy.lofi ~/.nginx/certs/live/api.symbology.lofi/fullchain.pem ~/.nginx/certs/live/api.symbology.lofi/privkey.pem --san "api.symbology.lofi" --not-after 24h

# âœ” Provisioner: tech@stev.lol (JWK) [kid: WGS0dsyrl9AFtm11F8Bs4bLccB7HEdgolAYTXfKkzBA]
# Please enter the password to decrypt the provisioner key:
# âœ” CA: https://ca.lofi:4443
# âœ” Certificate: /home/steven/.nginx/certs/live/v2.symbology.lofi/fullchain.pem
# âœ” Private Key: /home/steven/.nginx/certs/live/v2.symbology.lofi/privkey.pem
# âœ” Provisioner: tech@stev.lol (JWK) [kid: WGS0dsyrl9AFtm11F8Bs4bLccB7HEdgolAYTXfKkzBA]
# Please enter the password to decrypt the provisioner key:
# âœ” CA: https://ca.lofi:4443
# âœ” Certificate: /home/steven/.nginx/certs/live/api.v2.symbology.lofi/fullchain.pem
# âœ” Private Key: /home/steven/.nginx/certs/live/api.v2.symbology.lofi/privkey.pem
