global:
  resolve_timeout: "5m"

route:
  continue: false
  group_wait: "30s"
  group_interval: "5m"
  repeat_interval: "4h"
  receiver: "discord"

receivers:
  - name: "discord"
    discord_configs:
      - send_resolved: true
        webhook_url_file: /etc/alertmanager/discord_webhook_url
        # title: {{ template "discord.default.title" . }}
        # message: {{ template "discord.default.message" . }}
        # content: {{ template "discord.default.content" . }}
        username: Alertmanager
