modules:
  https_2xx:
    prober: http
    timeout: 5s
    http:
      headers:
        User-Agent: Blackbox-Exporter
      tls_config:
        insecure_skip_verify: false
      fail_if_not_ssl: true
  http_2xx:
    prober: http
    timeout: 5s
    http:
      headers:
        User-Agent: Blackbox-Exporter
  icmp:
    prober: icmp
    timeout: 5s
    icmp:
