global:
  scrape_interval: 45s
  evaluation_interval: 45s

rule_files:
  - /etc/prometheus/prometheus.rules.yaml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - 10.0.0.2:9090
    relabel_configs:
      - source_labels: [__address__]
        regex: 10.0.0.2:9090
        replacement: soundship
        target_label: instance

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - 10.0.0.1:9100
          - 10.0.0.2:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: 10.0.0.1:9100
        replacement: router
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.2:9100
        replacement: soundship
        target_label: instance

  - job_name: "macs"
    static_configs:
      - targets:
          - 10.0.0.95:9100
          - 10.0.0.96:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: 10.0.0.95:9100
        replacement: macbook-air
        target_label: instance
      - source_labels: [instance]
        regex: macbook-air
        replacement: en6
        target_label: ethernet_device
      - source_labels: [__address__]
        regex: 10.0.0.96:9100
        replacement: macmini
        target_label: instance
      - source_labels: [instance]
        regex: macmini
        replacement: en0
        target_label: ethernet_device

  - job_name: "linux_vms"
    static_configs:
      - targets:
          - 10.0.0.3:9100
          - 10.0.0.4:9100
          - 10.0.0.5:9100
          - 10.0.0.6:9100
          - 10.0.0.7:9100
          # staging
          - 10.0.0.21:9100
          - 10.0.0.22:9100
          - 10.0.0.24:9100
          - symbology.online:9100
          - fitz.gg:9100
    relabel_configs:
      - source_labels: [__address__]
        regex: 10.0.0.3:9100
        replacement: devbox
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.4:9100
        replacement: llm-server
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.5:9100
        replacement: lab-proxy
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.6:9100
        replacement: capm3-dev
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.7:9100
        replacement: custom-image-builder
        target_label: instance
      - source_labels: [__address__]
        regex: symbology.online:9100
        replacement: symbology-production
        target_label: instance
      - source_labels: [__address__]
        regex: fitz.gg:9100
        replacement: fitz.gg-production
        target_label: instance

      # staging
      - source_labels: [__address__]
        regex: 10.0.0.21:9100
        replacement: staging-1g
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.22:9100
        replacement: staging-2g
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.24:9100
        replacement: staging-4g
        target_label: instance

  - job_name: "windows_exporter"
    static_configs:
      - targets:
          - 10.0.0.99:9182
    relabel_configs:
      - source_labels: [__address__]
        regex: 10.0.0.99:9182
        replacement: win11
        target_label: instance
      - source_labels: [core]
        regex: ".*,([0-9]+)"
        target_label: foo
        action: replace

  - job_name: "nvidia_gpu_exporter"
    static_configs:
      - targets:
          - 10.0.0.4:9835
          - 10.0.0.99:9835
    relabel_configs:
      - source_labels: [__address__]
        regex: 10.0.0.4:9835
        replacement: llm-server
        target_label: instance
      - source_labels: [__address__]
        regex: 10.0.0.99:9835
        replacement: win11
        target_label: instance

  - job_name: "http_from_router"
    scrape_interval: 60s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - aws.amazon.com
          - portal.azure.com
          - cloudflare.com
          - cloud.google.com
          - cloud.linode.com
    relabel_configs:
      # relabel instance to target
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      # then scrape the exporter endpoint
      - target_label: __address__
        replacement: 10.0.0.1:9115

  - job_name: "https_from_soundship"
    metrics_path: /probe
    params:
      module: [https_2xx]
    static_configs:
      - targets:
          - https://symbology.online
          - https://fitz.gg
          - https://dial-in.fitz.gg
          - https://sketches.fitz.gg

    relabel_configs:
      # relabel instance to target
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      # then scrape the exporter endpoint
      - target_label: __address__
        replacement: 10.0.0.2:9115

  - job_name: "ollama_exporter"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - 10.0.0.4:8000

alerting:
  alertmanagers:
    - timeout: "10s"
      api_version: v2
      path_prefix: /
      scheme: http
      follow_redirects: true
      static_configs:
        - targets:
            - alertmanager:9093
